<?php


use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function mymodule_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom module.
    case 'help.page.mymodule':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('module for axelerant tasks') . '</p>';
      return $output;

    default:
  }
}


/*
*
* Implements hook_form_FORM-ID_alter
* This is to Add New Site API Key field in Site information page
*/
function mymodule_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state) {
  
  // by default sitepikey value will be fetched from setting file
  $siteapikey = \Drupal::config('mymodule.settings')->get('siteapikey');
  
  // adding new column Site API Key in site information form 
  $form['site_information']['siteapikey'] = array(
	'#type' => 'textfield',
	'#title' => t('Site Organization'),
	'#required' => TRUE,
	'#maxlength' => 255,
	'#default_value' => $siteapikey,
	'#description' => t('Site API Key to enter'),
  );

// changing the label of submit form
  $form['actions']['submit']['#value'] = t('Update Configuration');

  //Submit handler to store siteapikey value into mymodule.setting
  $form['#submit'][] = 'mymodule_siteinformation_submit_handler';
}


/*
*
* Implements handler
* This is to submit the form and store the sitapikeyvalue in mymodule.setting
*/
function mymodule_siteinformation_submit_handler(&$form, FormStateInterface $formState) {
 
  if( false == empty( $form['site_information']['siteapikey']['#value'] ) && $form['site_information']['siteapikey']['#value'] != \Drupal::config('mymodule.settings')->get('siteapikey') ) {

    \Drupal::configFactory()->getEditable('mymodule.settings')
      ->set('siteapikey', $form['site_information']['siteapikey']['#value'])
      ->save();
      \Drupal::messenger()->addStatus(t('Site API Key has been saved with value @site', ['@site' => $form['site_information']['siteapikey']['#value']]));
   
  }
} 